alias c="clear"

alias loadbash="source ~/.bashrc"
alias cdalias="cd ~/configs/dotfiles/"

alias cdnvim="cd ~/.config/nvim/"

alias cdp="cd ~/projects/"

alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gpull="git pull"
alias gpush="git push"
alias glog="git log"

alias zp="source ~/configs/dotfiles/scripts/zp.sh"
alias zc="source ~/configs/dotfiles/scripts/zc.sh"
alias zvim="fzf | xargs nvim"
alias zcat="fzf --preview 'cat {}' | xargs cat"

export PATH=$PATH:$HOME/devtools/Odin/
export PATH=$PATH:/var/lib/flatpak/exports/bin:$HOME/.local/share/flatpak/exports/bin/
